//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alexis.WindowsPhone.Social.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alexis.WindowsPhone.Social.Resources.LangResource", typeof(LangResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已绑定.
        /// </summary>
        public static string Binded {
            get {
                return ResourceManager.GetString("Binded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定QQ空间.
        /// </summary>
        public static string BindQzone {
            get {
                return ResourceManager.GetString("BindQzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定人人.
        /// </summary>
        public static string BindRenren {
            get {
                return ResourceManager.GetString("BindRenren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定腾讯微博.
        /// </summary>
        public static string BindTencent {
            get {
                return ResourceManager.GetString("BindTencent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定新浪微博.
        /// </summary>
        public static string BindWeibo {
            get {
                return ResourceManager.GetString("BindWeibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否要注销该帐号？.
        /// </summary>
        public static string LogOffConfirm {
            get {
                return ResourceManager.GetString("LogOffConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注销成功.
        /// </summary>
        public static string LogOffSuccess {
            get {
                return ResourceManager.GetString("LogOffSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享到.
        /// </summary>
        public static string ShareTo {
            get {
                return ResourceManager.GetString("ShareTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解除绑定.
        /// </summary>
        public static string UnBind {
            get {
                return ResourceManager.GetString("UnBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未绑定.
        /// </summary>
        public static string UnBinded {
            get {
                return ResourceManager.GetString("UnBinded", resourceCulture);
            }
        }
    }
}
